plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'com.example.fakegps'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.fakegps"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"

        // allow mock location
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.0"
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
